language: node_js
node_js: 
    - "stable"
sudo: true
dist: trusty


branches:
  only:
  - master

addons:
  chrome: stable

before_script: 
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules


 script: 
  - ng build --prod
  - ng build -bh "https://shamimsdp.github.io/ng7practice/"

  deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: 4f8982208cbe704b73f5c7371a105135ae461e5d # Set in travis-ci.org dashboard
  local_dir: ./dist/ng7mat
  on:
    branch: master
